### ISSUE TITLE
IV Calculation Question

### ISSUE THREAD

**Issue by TheBambino** [Boren/PokemonGO-IV-Renamer#1]
I have been comparing the results using this tool to other tools from sources like Sylph, but they are never the same. In many situations the stats are completely different and the levels are not close.

Can you give me an idea of what's going on here?

By the way, It works great.

**Comment by Boren** [comment]
This one fetches them directly from the API so they should be correct. Tools like the silph road calculator should get more or less the same numbers if you are precise with them.

**Comment by Boren** [comment]
TODO: Add a FAQ
