### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by dosin** [Boren/PokemonGO-IV-Renamer#10]
How to resolve **login error**
It's ok to use other bot

**Comment by Boren** [comment]
I'm going to need a bit more information to work with..

**Comment by RyuBcn** [comment]
Start renamer
Login error

and program stops, i changed main.py to get the prints with the python3.3 syntax i.e print "hello" to print("hello")

but now stuck on login error

**Comment by kasontroy** [comment]
I'm getting the same Login error. Running python 2.7.10 and using my google account.

**Comment by RyuBcn** [comment]
SOLVED!! it is because we use google accounts from server outside our country and google block the access, once you authorize again from your home and change password it works ok

**Comment by thisischrys** [comment]
so... close it?

protip: 2-factor authentication on your google account breaks this
