### ISSUE TITLE
Python2 not recognized ...

### ISSUE THREAD

**Issue by grandfroid** [Boren/PokemonGO-IV-Renamer#12]
Even after a clean install of Python 2.7.5 (I click to create the path), I still get 'Python2' is not recognised ... 
Any idea ?

**Comment by pperle** [comment]
try py -2

**Comment by ohh2ahh** [comment]
This is working for me (Python 2.7.10):

```
python main.py -a AUTH_SERVICE -u USERNAME -p PASSWORD
```
