### ISSUE TITLE
In Python 3.3 i got this error once connected

### ISSUE THREAD

**Issue by RyuBcn** [Boren/PokemonGO-IV-Renamer#13]
Start renamer
Signed in
Getting pokemon list
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    Renamer().start()
  File "main.py", line 46, in start
    self.get_pokemons()
  File "main.py", line 82, in get_pokemons
    reduce(dict.**getitem**, ["inventory_item_data", "pokemon_data"], item)
NameError: global name 'reduce' is not defined

**Comment by pperle** [comment]
please run the script with python2 as it was written in/for python2
