### ISSUE TITLE
The IV Renamer runs, but it doesn't rename in-game.

### ISSUE THREAD

**Issue by juliocorzo** [Boren/PokemonGO-IV-Renamer#16]
Possible Pokemon Go server changes? It worked a few days ago and the only thing that i've changed is 2-step verification which shouldn't be a problem because I was able to log in.

The script runs and the renamer tells me that it's renaming, but it isn't really doing anything.

**Comment by ademgcl** [comment]
same problem here; renamer says renaming but doing nothing

**Comment by Boren** [comment]
Just tested latest version here and it works like it should. I'll get to adding some more debug info soon.

**Comment by ademgcl** [comment]
updated the version now it says:
"Something went wrong with renaming Meowth (CP 348) to Meowth40. Error code: 3"

any idea about what code 3 may be?

**Comment by Boren** [comment]
Code 3 is "Pokemon not found". Means the wrong ID was supplied. I'm unable to find the exact reason for it right now. If you know how to do it, you could try to debug a little on your end to get more information.

**Comment by ademgcl** [comment]
debugged -though i am not a python developer- parameters passed seems to be alright, still error code 3 though

req_method_list:
{'nickname': u'Vaporeon88', 'pokemon_id': 12936188303765164305L}

**Comment by Boren** [comment]
Do a new "pip install -r requirements.txt"

**Comment by ademgcl** [comment]
thanks fredrik, resolved. sorry for taking your time
