### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by dosin** [Boren/PokemonGO-IV-Renamer#18]
Start renamer
Signed in
Getting pokemon list

--------- Venusaur ---------
CP 33 - 0/14/7 46.67%
CP 1150 - 0/2/2 8.89%

--------- Charmeleon ---------
CP 725 - 0/13/1 31.11%

--------- Squirtle ---------
CP 91 - 0/13/13 57.78%

--------- Wartortle ---------
CP 918 - 0/7/14 46.67%

--------- Metapod ---------
CP 215 - 0/13/7 44.44%

--------- Butterfree ---------
CP 858 - 0/11/5 35.56%

--------- Weedle ---------
CP 208 - 0/7/14 46.67%

--------- Kakuna ---------
CP 76 - 1/13/15 64.44%

--------- Beedrill ---------
CP 330 - 2/9/15 57.78%

--------- Pidgey ---------
CP 239 - 3/11/4 40.00%

--------- Pidgeotto ---------
CP 222 - 6/15/14 77.78%

--------- Pidgeot ---------
CP 442 - 5/13/14 71.11%
CP 1120 - 3/14/0 37.78%

--------- Rattata ---------
CP 96 - 8/12/4 53.33%
CP 66 - 7/12/4 51.11%

--------- Raticate ---------
CP 144 - 8/14/15 82.22%

--------- Spearow ---------
CP 215 - 6/13/15 75.56%
CP 60 - 6/7/5 40.00%

--------- Fearow ---------
CP 23 - 6/15/14 77.78%
CP 1178 - 13/1/15 64.44%

--------- Ekans ---------
CP 305 - 7/12/15 75.56%

--------- Arbok ---------
CP 901 - 7/13/12 71.11%
CP 1028 - 2/5/10 37.78%

--------- Sandshrew ---------
CP 162 - 7/13/12 71.11%

--------- Sandslash ---------
CP 71 - 2/1/15 40.00%
Traceback (most recent call last):
  File "main.py", line 204, in <module>
    Renamer().start()
  File "main.py", line 55, in start
    self.print_pokemons()
  File "main.py", line 130, in print_pokemons
    print "\n--------- " + self.pokemon_list[str(key)] + " ---------"
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2640' in position 18: ordinal not in range(128)

**Comment by pperle** [comment]
fixed it yesterday, please see https://github.com/Boren/PokemonGO-IV-Renamer/pull/15
