### ISSUE TITLE
[Suggestions] Use % rather than 45, Clear option

### ISSUE THREAD

**Issue by vamirineni87** [Boren/PokemonGO-IV-Renamer#2]
Could be added as a parameter.
option to clear the IVs

**Comment by Boren** [comment]
Will work on this next :)

**Comment by Boren** [comment]
Option to clear names added in commit 07a318f62fc396cd06a2f41260e30d0b4110a76a

**Comment by Boren** [comment]
Custom formatting added in commit 8042401acf3fd6dd097e95e5ee8550f73d292bca
