### ISSUE TITLE
UnicodeError During Rename

### ISSUE THREAD

**Issue by sahayes1** [Boren/PokemonGO-IV-Renamer#21]
During rename the same Unicode Error that was fixed earlier is an issue.

--------- Bellsprout ---------
CP 14 - 14/2/11 60.00%
CP 165 - 10/4/12 57.78%

--------- Ponyta ---------
CP 340 - 15/15/14 97.78%

--------- Slowpoke ---------
CP 209 - 5/13/2 44.44%

--------- Gastly ---------
CP 133 - 14/3/3 44.44%

--------- Drowzee ---------
CP 44 - 14/2/13 64.44%

--------- Krabby ---------
CP 99 - 7/14/14 77.78%

--------- Exeggcute ---------
CP 204 - 15/6/11 71.11%
CP 139 - 14/2/13 64.44%

--------- Goldeen ---------
CP 41 - 15/6/14 77.78%
CP 202 - 10/11/11 71.11%
CP 199 - 15/4/6 55.56%

--------- Staryu ---------
CP 39 - 13/9/13 77.78%
CP 158 - 15/2/2 42.22%

--------- Magmar ---------
CP 429 - 11/11/15 82.22%

--------- Pinsir ---------
CP 588 - 14/12/10 80.00%
CP 83 - 4/0/10 31.11%

--------- Magikarp ---------
CP 10 - 5/1/4 22.22%

--------- Eevee ---------
CP 273 - 14/15/15 97.78%
CP 14 - 9/15/14 84.44%
CP 107 - 15/13/6 75.56%
CP 14 - 12/4/15 68.89%
CP 106 - 15/3/11 64.44%
CP 74 - 15/9/3 60.00%
CP 195 - 15/9/3 60.00%
CP 134 - 15/11/0 57.78%
CP 284 - 14/2/9 55.56%
CP 158 - 8/0/14 48.89%
CP 182 - 4/0/15 42.22%
Renaming Oddish (CP 46) to 55% Oddish
Renaming Slowpoke (CP 209) to 44% Slowpoke
Renaming Rattata (CP 113) to 20% Rattata
Renaming Pidgey (CP 42) to 44% Pidgey
Renaming Venonat (CP 101) to 73% Venonat
Renaming Goldeen (CP 41) to 77% Goldeen
Renaming Pidgey (CP 100) to 11% Pidgey
Renaming Rattata (CP 21) to 46% Rattata
Renaming Drowzee (CP 44) to 64% Drowzee
Renaming Meowth (CP 154) to 60% Meowth
Renaming Pinsir (CP 83) to 31% Pinsir
Renaming Paras (CP 11) to 46% Paras
Renaming Caterpie (CP 97) to 91% Caterpie
Renaming Pidgey (CP 90) to 31% Pidgey
Traceback (most recent call last):
  File "main.py", line 204, in <module>
    Renamer().start()
  File "main.py", line 62, in start
    self.rename_pokemons()
  File "main.py", line 168, in rename_pokemons
    print "Renaming " + pokemon_name + " (CP " + str(pokemon['cp'])  + ") to " + name
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2642' in position 16: character maps to <undefined>

**Comment by Brideau** [comment]
Saw this as well when running this on a Windows box, since I believe it's encoding isn't UTF-8 by default.

**Comment by sahayes1** [comment]
Any simple solution for it. At the minimum could we make it skip over those Pokemon instead of error out? 

Thanks,
Steven Hayes
A+, Network+, Server+, Security+
MCITP Enterprise Administrator
MCTS SharePoint 2010 Administrator
MCTS Exchange 2010 Administrator
PMP (Project Management Professional)

On Aug 1, 2016, at 8:56 AM, Ryan Brideau notifications@github.com wrote:

Saw this as well when running this on a Windows box, since I believe it's encoding isn't UTF-8 by default.

**Comment by pperle** [comment]
please update to latest version as this problem has already been fixed see https://github.com/Boren/PokemonGO-IV-Renamer/pull/15
