### ISSUE TITLE
New version does not work

### ISSUE THREAD

**Issue by TheBambino** [Boren/PokemonGO-IV-Renamer#23]
I would recommend going back to the initial release and adding a longer delay between renames. Many of them get messed after Pokemon Go place some limitation on the API recently.

The new version crashes on Sandlash. Issue with naming "Sandslash."

**Comment by Boren** [comment]
d0bea3f41466afa2a4f911e5594c5ac673429004 adds configurable delay and extends default delay from 2 to 4 seconds.
