### ISSUE TITLE
Odd Characters in Pokemon List Text

### ISSUE THREAD

**Issue by sahayes1** [Boren/PokemonGO-IV-Renamer#25]
Seeing brackets and 0m and things on list after running the command now.

--------- Nidoran(M) ---------
CP 103 - 10/12/6 62.22%

--------- Nidorino ---------
[92mCP 619 - 10/15/12 82.22%[0m
CP 159 - 7/0/4 24.44%

--------- Clefairy ---------
[92mCP 232 - 10/14/3 60.00%[0m
CP 406 - 6/2/12 44.44%
CP 169 - 5/1/8 31.11%

--------- Vulpix ---------
CP 389 - 13/10/10 73.33%

--------- Jigglypuff ---------
[92mCP 420 - 13/14/13 88.89%[0m
CP 406 - 15/12/10 82.22%

--------- Zubat ---------
CP 289 - 10/10/15 77.78%

--------- Golbat ---------
[92mCP 793 - 14/15/5 75.56%[0m
CP 653 - 11/12/9 71.11%

**Comment by Boren** [comment]
Those characters are added for color purposes and should display a color on most operating systems.

Which operating system are you?
What terminal are you using?
Python version?

**Comment by sahayes1** [comment]
Windows 10 anniversary update
Command prompt.
Latest Python 2.6 version. 

I'll test on my other machines. It was working fine. I wonder if this is because of the anniversary update. 

Thanks,
Steven Hayes
A+, Network+, Server+, Security+
MCITP Enterprise Administrator
MCTS SharePoint 2010 Administrator
MCTS Exchange 2010 Administrator
PMP (Project Management Professional)

On Aug 3, 2016, at 8:20 AM, Fredrik Bore notifications@github.com wrote:

Those characters are added for color purposes and should display a color on most operating systems.

Which operating system are you?
What terminal are you using?
Python version?
