### ISSUE TITLE
Name reset translations

### ISSUE THREAD

**Issue by ohh2ahh** [Boren/PokemonGO-IV-Renamer#5]
First of all, thanks for your easy to use IV renamer. I really like the ability to reset the Pokémon's names. It would be even better if you could add translations of the names and allow us to specifiy the language, e.g. `--clear de` for german names (english als default if the user doesn't specifiy a language).

Edit: `%name` should be translated aswell.

Maybe you can use the translations from [PokemoGo-Map](https://github.com/AHAAAAAAA/PokemonGo-Map/tree/master/static/locales).

**Comment by Boren** [comment]
I was hestitant to do this, but with the files from PokemonGo-Map I will do this when I have time.
