### ISSUE TITLE
Rename without location

### ISSUE THREAD

**Issue by AntoineReneleau** [Boren/PokemonGO-IV-Renamer#57]
Is location really mandatory?
Couldn't we rename being in the state of "GPS signal not found"?

**Comment by AntoineReneleau** [comment]
I found this https://github.com/keyphact/pgoapi/issues/43 showing that with the new version of the api you can't login without location.
But was it mandatory to update the api since it kept working without it?

**Comment by Boren** [comment]
The latest API the project is based on requires it. I've yet to investigate why, but will do when I got time.
