### ISSUE TITLE
Show only the list of IVs without renaming the Pokémons

### ISSUE THREAD

**Issue by ohh2ahh** [Boren/PokemonGO-IV-Renamer#6]
Only show the current output without renaming the Pokémons, mybe with `--list_only` and/or `-lo`.

**Comment by dosin** [comment]
same here

**Comment by michallaskowski** [comment]
I am already working on this, though I am not really good in Python, current output is like that

```
--------- Goldeen ---------
CP 88 - 5/11/7 51.11%
CP 350 - 4/4/8 35.56%

--------- Staryu ---------
CP 137 - 10/9/6 55.56%
CP 294 - 9/0/5 31.11%

--------- Jynx ---------
CP 631 - 15/15/12 93.33%

--------- Magikarp ---------
CP 111 - 11/15/15 91.11%
```

I want to make the one with the best stats to be in bold. What do you think? I could prepare a PR.

**Comment by Boren** [comment]
Looks good! I won't have time to work much on this until next week so feel free to send a PR and I'll review it.

The list could be printed every time and give the user a option to continue with the renaming.

**Comment by Boren** [comment]
Added in b68ac1a7660ee73e20b2260ef97f4cbded388a65
