### ISSUE TITLE
Some Pokemon cannot rename correctly

### ISSUE THREAD

**Issue by imyhxy** [Boren/PokemonGO-IV-Renamer#64]
Some Pokemon have a long name, like Jigglypuff. When use the -format "%name %percent" to rename the Pokemon, it will get a wrong result. For example, Jigglypuff have a 90%IV and the result is "Jigglypuff 9", it seems that the name is over the limit.

**Comment by tegob** [comment]
From the README: https://github.com/Boren/PokemonGO-IV-Renamer#placeholders-for---format

> automatically gets cropped to 12 characters

**Comment by imyhxy** [comment]
I hope it can crop the %name only.

**Comment by tegob** [comment]
If that’s what you want, why don’t you just use `--format "%percent %name"` instead?
