### ISSUE TITLE
Can't rename Nidoran

### ISSUE THREAD

**Issue by NGPriest** [Boren/PokemonGO-IV-Renamer#67]
File "main.py", line 282, in <module>
    Renamer().start()
  File "main.py", line 77, in start
    self.rename_pokemon()
  File "main.py", line 215, in rename_pokemon
    print "Renaming " + pokemon_name.replace(u'\N{MALE SIGN}', '(M)').replace(u'\N{FEMALE SIGN}', '(F)') + " (CP " + str(pokemon['cp'])  + ") to " + name
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2642' in position 42: ordinal not in range(128)

**Comment by pkchukiss** [comment]
The `name` string for Nidoran contains unprintable characters, which needs to be replaced.

As a temporary fix, change line 215 to:
`print "Renaming " + pokemon_name.replace(u'\N{MALE SIGN}', '(M)').replace(u'\N{FEMALE SIGN}', '(F)') + " (CP " + str(pokemon['cp'])  + ") to " + name.replace(u'\N{MALE SIGN}', '(M)').replace(u'\N{FEMALE SIGN}', '(F)')`

**Comment by edevnull** [comment]
Got same issue:

`Traceback (most recent call last):
  File "main.py", line 282, in <module>
    Renamer().start()
  File "main.py", line 77, in start
    self.rename_pokemon()
  File "main.py", line 215, in rename_pokemon
    print "Renaming " + pokemon_name.replace(u'\N{MALE SIGN}', '(M)').replace(u'\N{FEMALE SIGN}', '(F)') + " (CP " + str(pokemon['cp'])  + ") to " + name
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2640' in position 39: ordinal not in range(128)
`
