### ISSUE TITLE
How to stop renaming already named pokemon?

### ISSUE THREAD

**Issue by Rediculocity** [Boren/PokemonGO-IV-Renamer#71]
I love your script and have been using it for months.

I slowly add characters to my Pokemon names, to differentiate them for many reasons like if they have a particular move set that I like. However when I run your script it renames all Pokemon that don't already match the format called out by the --format argument. I was looking through the code and it looks like it it might be possible to have it only rename Pokemon without a nickname already. Is this possible with some tweaking? Is it already supposed to do this? forgive my incompetence, if I have overlooked something.

**Comment by deana14** [comment]
This is actually very easy to do and the options are already implemented in the code, you just have to enable it. At lines 52-54 of the current main.py file you should see:

```
  self.config.overwrite =True

  #self.config.skip_favourite = True

  #self.config.only_favorite = False
```

Change `self.config.overwrite` to `False` will only rename Pokemon that are not nicknamed. You can uncomment 1 of the last 2 lines to either skip renaming favourites or rename only favourites.

**Comment by Rediculocity** [comment]
Thanks so much! That worked perfectly. Also thanks for the quick response, and you can close this issue.
