### ISSUE TITLE
New API needed

### ISSUE THREAD

**Issue by GMNGT** [Boren/PokemonGO-IV-Renamer#72]
IV-Renamer can log in but doesn't list any pokemon.

**Comment by travisfisher** [comment]
+1

**Comment by Boren** [comment]
This project isn't really updated anymore. Feel free to submit a PR and I'll review it.

**Comment by tegob** [comment]
PR: https://github.com/Boren/PokemonGO-IV-Renamer/pull/73

**Comment by GMNGT** [comment]
The updated requirements.txt file worked for me, thanks.
