### ISSUE TITLE
No Pokémon found

### ISSUE THREAD

**Issue by tegob** [Boren/PokemonGO-IV-Renamer#76]
Did something change about the API again?

Logging in still works this time, but the script seems to think there are no Pokémon in the inventory. (The account isn’t banned.)

**Comment by yujiahuang** [comment]
From this issue: [https://github.com/pogodevorg/pgoapi/issues/183](https://github.com/pogodevorg/pgoapi/issues/183), this pull request ([https://github.com/pogodevorg/pgoapi/pull/184](https://github.com/pogodevorg/pgoapi/pull/184)) fixed it. You can change the code manually if you're in a hurry. (eg. your storage is full, just like me),or wait for pgoapi to merge the PR.

**Comment by tegob** [comment]
@yujiahuang That fix worked for a while but now it seems something changed again. :(

**Comment by tegob** [comment]
https://www.reddit.com/r/pokemongodev/comments/5ymc2h/is_45_gone_for_good/
